# Generated by Django 3.2 on 2022-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ler', models.CharField(max_length=200)),
            ],
        ),
    ]
